### ISSUE TITLE
Up and Down Arrows don't accomodate for lines with short letters

### ISSUE THREAD

**Issue by yecki** [MrX13415/TypeEx#17]
example
iiiiiii|iiiii

(up from the | jumps to end of first line in this case (also down on end of first line back to that |)

**Comment by MrX13415** [comment]
The cursor position, currently only uses the chracter position in the text. To improve this the pixel position should be used instead.

**Comment by MrX13415** [comment]
Implemented with commit eb7037badb5f5823cde2fb20cd9f014923579cc8
